# Generated by Django 3.2.7 on 2021-09-29 07:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(max_length=60, upload_to='documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('status', models.CharField(choices=[('processing', '1'), ('done', '2')], default='processing', max_length=10)),
                ('pages', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_num', models.IntegerField()),
                ('page_img', models.ImageField(upload_to='images')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service_app.document')),
            ],
        ),
    ]
