# Generated by Django 3.2.7 on 2021-09-24 10:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='inserted',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
