# Generated by Django 3.2.7 on 2021-09-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0002_alter_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='document_id',
            new_name='document',
        ),
    ]
