# Generated by Django 3.2.7 on 2021-09-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0003_rename_document_id_page_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
