# Generated by Django 3.2.7 on 2021-09-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0004_alter_page_page_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=60, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_img',
            field=models.ImageField(upload_to='images'),
        ),
    ]
