# Generated by Django 3.2.7 on 2021-09-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0005_auto_20210926_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='pages',
            field=models.IntegerField(default=None),
        ),
    ]
