# Generated by Django 3.2.7 on 2021-09-26 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0007_alter_document_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('processing', '1'), ('done', '2')], default='processing', max_length=10),
        ),
    ]
