# Generated by Django 3.2.7 on 2021-09-28 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0008_alter_document_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=60, upload_to='documents', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
