# Generated by Django 3.2.7 on 2021-09-28 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_app', '0009_alter_document_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='file',
            new_name='pdf_file',
        ),
    ]
